#!/usr/bin/env python

import os
import sys
import subprocess
import argparse
import getpass
import hashlib

parser = argparse.ArgumentParser()
    
parser.add_argument('action',
                    help='start|stop|show',
                    default=None
                    )

parser.add_argument('--https',
                    help='Enable secure mode',
                    action='store_true',
                    default=False
                    )

parser.add_argument('--dbpass',
                    help='Password for database',
                    default=None
                    )

parser.add_argument('--local',
                    help='Connect to a localhost database',
                    action='store_true',
                    default=False
                    )

args = parser.parse_args()

# Starts all the necessary server components as a background process
# Also allows to reattach to the multiplexed terminal,
# and to kill the process

screen_name = 'alabnodaemonservice'

# exec dir is alabno/
exec_dir = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))
os.chdir(exec_dir)

# import git authentication library
sys.path.append(os.path.abspath(exec_dir + os.sep + 'infrastructure'))
import gitauth

def start_server(https):
    global args
    if args.local:
        os.environ["ALABNOLOCAL"] = "1"
    else:
        os.environ["ALABNOLOCAL"] = "2"
    
    # Setup git authentication
    gitauth.ask_authentication()
    gitauth.set_auth_passphrase()
    
    if https:
        # Ask the keystore password
        print('Please enter the java keystore password')
        keystorepass = getpass.getpass()
        os.environ["ALABNOJKSPASS"] = keystorepass
        
        print("Starting in secure mode")
        # check for presence of certificates
        if not os.path.isfile('frontend/mykeystore.jks'):
            print("Certificates not found. Generating self-signed certificates now...")
            subprocess.call('cd frontend && ./generate_certificates.sh', shell=True)
        start_server_command = './infrastructure/runservers_secure.sh'
    else:
        print("Starting in normal mode")
        start_server_command = './infrastructure/runservers.sh'
    cmd = 'screen -A -m -d -S {} {}'.format(screen_name, start_server_command)
    subprocess.call(cmd, shell=True)

def kill_server():
    cmd = 'screen -X -S {} quit'.format(screen_name)
    subprocess.call(cmd, shell=True)

def show_server():
    print('If server is running, you will be attached to its console')
    print('To exit the server console without killing it, press')
    print('Ctrl+A, then press D')
    print('Press ENTER to continue...')
    raw_input()
    cmd = 'screen -r {}'.format(screen_name)
    subprocess.call(cmd, shell=True)

def exit_with_error():
    parser.print_help()
    sys.exit(1)

def pass_correct(the_pass):
    correct_password_hash = 'bec67085f3ce2ca2174b1d7d62d7e316'
    m = hashlib.md5()
    m.update(the_pass)
    new_password_hash = m.hexdigest()
    result = correct_password_hash == new_password_hash
    if not result:
        print('Password not correct. Retry')
    return result

https = args.https

command = args.action

# Ask for password if necessary
if not os.path.isfile(exec_dir + os.sep + 'dbpass.txt'):
    the_pass = ''
    if args.dbpass is None:
        password_correct = False
        while not password_correct:
            print('Please enter the password for the database account "python"')
            the_pass = getpass.getpass()
            password_correct = pass_correct(the_pass)
    else:
        the_pass = args.dbpass

    pass_path = exec_dir + os.sep + 'dbpass.txt'
    pass_file = open(pass_path, 'w')
    pass_file.write(the_pass)
    pass_file.close()

# Start the server
if command == 'show':
    show_server()
elif command == 'start':
    start_server(https)
elif command == 'stop':
    kill_server()
else:
    exit_with_error()
