#!/usr/bin/env python

import os
import subprocess
import sys
from random import randint

tmp_dir = '/tmp/'

# Makes it possible to execute the script from anywhere and still be able to
# correctly locate the classpaths
exec_dir = os.path.abspath(os.path.dirname(os.path.abspath(__file__)) + os.sep + '..' + os.sep + '..')

os.chdir(exec_dir)

java_proj_path = 'infrastructure' + os.sep + 'infrastructure' + os.sep

target_jar = java_proj_path + os.sep + 'target' + os.sep + 'infrastructure-dev.0.1-jar-with-dependencies.jar'

classpath = [
    java_proj_path + 'config',
    target_jar
    ]

classpath_joint = ':'.join(classpath)

cmd = 'java -cp "{}" alabno.wserver.Main'.format(classpath_joint)

code = subprocess.call(cmd, shell=True)

sys.exit(code)
